import { useEffect, useState } from 'react';
import Layout from '../components/Layout';
import * as userService from '../services/userService';

const empty = { name: '', email: '', phone: '', password: '', role: 'staff', is_active: true };

export default function Users() {
  const [users, setUsers] = useState([]);
  const [form, setForm] = useState(null);
  const [error, setError] = useState('');
  const [saving, setSaving] = useState(false);
  const load = async () => { try { setUsers(await userService.getUsers()); } catch (e) { setError(e.response?.data?.error || 'Could not load users.'); } };
  useEffect(() => { load(); }, []);
  const update = (key, value) => setForm((f) => ({ ...f, [key]: value }));
  async function submit(e) { e.preventDefault(); setSaving(true); try { const { id, ...payload } = form; if (id) await userService.updateUser(id, payload); else await userService.createUser(payload); setForm(null); await load(); } catch (err) { setError(err.response?.data?.error || 'Could not save user.'); } finally { setSaving(false); } }
  async function removeUser(user) { if (!confirm(`Delete ${user.name}? Their stock-movement history is kept without their account name.`)) return; try { await userService.deleteUser(user.id); await load(); } catch (err) { setError(err.response?.data?.error || 'Could not delete user.'); } }

  return <Layout title="User Management"><div className="flex justify-between mb-5"><p className="text-sm text-ink/60">Create accounts, change roles, update contact details, disable, or delete users.</p><button onClick={() => setForm(empty)} className="bg-ink text-paper px-4 py-2 font-mono text-xs uppercase">+ Add user</button></div>{error && <p className="text-brick text-sm mb-3">{error}</p>}<div className="bg-white border border-line overflow-x-auto"><table className="w-full text-sm"><thead className="text-left bg-paper-dim"><tr><th className="p-3">User</th><th className="p-3">Phone</th><th className="p-3">Role</th><th className="p-3">Status</th><th className="p-3">Actions</th></tr></thead><tbody>{users.map((u) => <tr key={u.id} className="border-t border-line"><td className="p-3"><b>{u.name}</b><br /><span className="text-ink/55">{u.email}</span></td><td className="p-3">{u.phone || '—'}</td><td className="p-3 capitalize">{u.role}</td><td className="p-3">{u.is_active ? 'Active' : 'Disabled'}</td><td className="p-3 flex gap-2"><button onClick={() => setForm({ ...u, password: '' })} className="border border-line px-2 py-1 font-mono text-xs">Edit</button><button onClick={() => removeUser(u)} className="border border-brick/40 text-brick px-2 py-1 font-mono text-xs">Delete</button></td></tr>)}</tbody></table></div>{form && <div className="fixed inset-0 z-50 bg-ink/60 flex items-center justify-center p-4"><form onSubmit={submit} className="bg-paper p-6 w-full max-w-md flex flex-col gap-3"><h2 className="font-display text-xl">{form.id ? 'Edit User' : 'Add User'}</h2><input required placeholder="Name" value={form.name} onChange={(e) => update('name', e.target.value)} className="border border-line p-2"/><input required type="email" placeholder="Email" value={form.email} onChange={(e) => update('email', e.target.value)} className="border border-line p-2"/><input placeholder="Phone (080... or +234...)" value={form.phone || ''} onChange={(e) => update('phone', e.target.value)} className="border border-line p-2"/><input required={!form.id} type="password" placeholder={form.id ? 'New password (optional)' : 'Password'} value={form.password} onChange={(e) => update('password', e.target.value)} className="border border-line p-2"/><select value={form.role} onChange={(e) => update('role', e.target.value)} className="border border-line p-2"><option value="staff">Staff</option><option value="manager">Manager</option><option value="admin">Admin</option></select>{form.id && <label className="text-sm"><input type="checkbox" checked={form.is_active} onChange={(e) => update('is_active', e.target.checked)} /> Account active</label>}<div className="flex gap-2"><button disabled={saving} className="flex-1 bg-ink text-paper p-2">{saving ? 'Saving…' : 'Save'}</button><button type="button" onClick={() => setForm(null)} className="flex-1 border border-line">Cancel</button></div></form></div>}</Layout>;
}
